"""
RealityScan CLI command whitelist.

Why this exists: an unrecognised command (a typo, or a command newer than the
installed build) raises a MODAL error dialog even under -headless, and the
process hangs until a human clicks it. Validating before spawn is the fix.

Source: the "All commands" page of the RealityScan documentation
(dev.epicgames.com/documentation/realityscan/all-commands), scraped 2026-09-22.
208 commands. Regenerate with tools/scrape_commands.py when the docs change.
Bypass per call with validate=False for commands the docs have not caught up with.
"""

from __future__ import annotations

import re

KNOWN_COMMANDS: frozenset[str] = frozenset({
    "-headless",
    "-hideUI",
    "-showUI",
    "-newScene",
    "-load",
    "-save",
    "-start",
    "-unlockPPIProject",
    "-add",
    "-addFolder",
    "-importVideo",
    "-importLeicaBlk3D",
    "-importLaserScan",
    "-importLaserScanFolder",
    "-importHDRimages",
    "-addImageWithCalibration",
    "-importImageSelection",
    "-selectImage",
    "-selectAllImages",
    "-deselectAllImages",
    "-invertImageSelection",
    "-removeCalibrationGroups",
    "-generateAIMasks",
    "-exportMasks",
    "-setImageLayer",
    "-setImagesLayer",
    "-removeImageLayer",
    "-importCache",
    "-clearCache",
    "-execRSCMD",
    "-quit",
    "-setFeatureSource",
    "-enableAlignment",
    "-enableMeshing",
    "-enableTexturingAndColoring",
    "-setWeightInTexturing",
    "-enableColorNormalizationReference",
    "-enableColorNormalization",
    "-setDownscaleForDepthMaps",
    "-enableInComponent",
    "-setCalibrationGroupByExif",
    "-setConstantCalibrationGroups",
    "-lockPoseForContinue",
    "-setPriorCalibrationGroup",
    "-setPriorLensGroup",
    "-editInputSelection",
    "-setInstanceName",
    "-delegateTo",
    "-waitCompleted",
    "-getStatus",
    "-pauseInstance",
    "-unpauseInstance",
    "-abortInstance",
    "-execRSCMDIndirect",
    "-align",
    "-draft",
    "-update",
    "-detectFeatures",
    "-mergeComponents",
    "-exportXMP",
    "-exportXMPForSelectedComponent",
    "-importComponent",
    "-importBundler",
    "-importColmap",
    "-exportLatestComponents",
    "-setMinComponentSize",
    "-exportSelectedComponentDir",
    "-exportSelectedComponentFile",
    "-exportRegistration",
    "-exportUndistortedImages",
    "-exportSTMap",
    "-exportSparsePointCloud",
    "-selectComponent",
    "-selectMaximalComponent",
    "-selectComponentWithLeastReprojectionError",
    "-renameSelectedComponent",
    "-deleteSelectedComponent",
    "-deleteComponent",
    "-deleteAllComponents",
    "-importFlightLog",
    "-importGroundControlPoints",
    "-importControlPointsMeasurements",
    "-editControlPointSelection",
    "-listControlPoints",
    "-selectControlPoint",
    "-invertControlPointSelection",
    "-renameControlPoint",
    "-renameSelectedControlPoint",
    "-deleteControlPoint",
    "-selectMeasurementByError",
    "-selectMeasurementByIndex",
    "-deleteControlPointMeasurement",
    "-exportGroundControlPoints",
    "-exportControlPointsMeasurements",
    "-defineDistance",
    "-editConstraintSelection",
    "-deleteConstraint",
    "-detectMarkers",
    "-setCamerasGravityDirection",
    "-resetGround",
    "-setGroundPlaneFromReconstructionRegion",
    "-setReconstructionRegionAuto",
    "-setReconstructionRegion",
    "-setReconstructionRegionOnCPs",
    "-setReconstructionRegionByDensity",
    "-scaleReconstructionRegion",
    "-moveReconstructionRegion",
    "-rotateReconstructionRegion",
    "-offsetReconstructionRegion",
    "-exportReconstructionRegion",
    "-calculatePreviewModel",
    "-calculateNormalModel",
    "-calculateHighModel",
    "-continueModelCalculation",
    "-selectModel",
    "-deleteSelectedModel",
    "-duplicateSelectedModel",
    "-renameSelectedModel",
    "-correctColors",
    "-unwrap",
    "-calculateTexture",
    "-calculateQualityTexture",
    "-reprojectTexture",
    "-calculateVertexColors",
    "-calculatePreviewVertexColors",
    "-calculateQualityColors",
    "-simplify",
    "-smooth",
    "-closeHoles",
    "-cleanModel",
    "-selectTrianglesInsideReconReg",
    "-selectTrianglesOutsideReconReg",
    "-selectMarginalTriangles",
    "-selectLargeTrianglesAbs",
    "-selectLargeTrianglesRel",
    "-selectLargestModelComponent",
    "-invertTrianglesSelection",
    "-deselectModelTriangles",
    "-removeSelectedTriangles",
    "-cutByBox",
    "-exportModel",
    "-exportSelectedModel",
    "-exportModelToZip",
    "-importModel",
    "-calculateOrthoProjection",
    "-selectOrthoProjection",
    "-editOrthoProjectionSelection",
    "-exportOrthoProjection",
    "-calculateCrossSections",
    "-exportCrossSections",
    "-renameCrossSections",
    "-selectCrossSections",
    "-computeContours",
    "-exportContours",
    "-renameContours",
    "-selectContours",
    "-exportShapes",
    "-importShapesToSelectedOrtho",
    "-importShapesToOrtho",
    "-selectShape",
    "-addShapeToSelection",
    "-exportReport",
    "-printReport",
    "-generateMaskFromMesh",
    "-exportMapsAndMask",
    "-exportLod",
    "-export3dTiles",
    "-exportCameraSnapshots",
    "-exportSelectedCamerasSnapshots",
    "-renderMeshFromCustomPositionYPR",
    "-renderMeshFromCustomPositionLookAt",
    "-renderMeshFromCustomGridPositionYPR",
    "-renderMeshFromCustomGridPositionLookAt",
    "-uploadToSketchfab",
    "-dtmClassify",
    "-selectClassification",
    "-renameSelectedClassification",
    "-transferClassification",
    "-exportClassificationSettings",
    "-importClassificationSettings",
    "-overrideSelectedVertices",
    "-selectClass",
    "-deselectClass",
    "-renameSelectedClass",
    "-setSelectedClassAsGroundForDTM",
    "-setSelectedClassAsGroundForExport",
    "-setSelectedClassLasFormat",
    "-selectVerticesOfSelectedClass",
    "-selectClassificationFormat",
    "-renameSelectedClassificationFormat",
    "-exportSelectedClassificationFormat",
    "-exportClassificationFormat",
    "-importClassificationFormat",
    "-colorModelBySelectedClassification",
    "-deleteSelectedClassification",
    "-set",
    "-preset",
    "-reset",
    "-silent",
    "-writeProgress",
    "-printProgress",
    "-tag",
    "-stdConsole",
    "-disableOnlineCommunication",
    "-importGlobalSettings",
    "-exportGlobalSettings",
    "-setProjectCoordinateSystem",
    "-setOutputCoordinateSystem",
})

# A value token starting with "-" is legitimate only when it is a negative number
# (e.g. -moveReconstructionRegion -1.5 0 0).
_NUMERIC = re.compile(r"^-\d")


def unknown_commands(tokens) -> list[str]:
    """Return the tokens that look like commands but are not in the whitelist."""
    bad = []
    for tok in tokens:
        s = str(tok)
        if s.startswith("-") and not _NUMERIC.match(s) and s not in KNOWN_COMMANDS:
            bad.append(s)
    return bad
